---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": ">=2.5.1"
license_file: LICENSE
name: ioscm
namespace: community
description: Ansible Network Collection for Cisco IOS devices.
readme: README.md
repository: https://github.com/ansible-collections/community.ioscm
issues: https://github.com/ansible-collections/community.ioscm/issues
tags: [cisco, ioscm, iosxe, networking, controller-mode, sd-wan]
# NOTE(pabelanger): We create an empty version key to keep ansible-galaxy
# happy. We dynamically inject version info based on git information.
version: "1.0.0"
